- 👋 Hi, I’m @FireBlaze360308YT
- 
- 👀 I’m interested in coding, reading and gaming
- 🌱 I’m currently learning python and i want to get good at it, i have previous knowledge of other programming languages
- 
- 💞️ I’m open to collaborate on project but be aware that i'm still learning
- 📫 How to reach me ...
- 
- 😄 Pronouns: he/him
- ⚡ Fun fact: i like italian pizza
